### ISSUE TITLE
does not work with arduino 1.8.15

### ISSUE THREAD

**Issue by cybergrunge-ops** [9glt/arduino-attiny85-fastpin-library#1]
/home/ellie/Arduino/libraries/attiny85FasterPin/src/Attiny85FasterPin.cpp: In constructor 'Attiny85FasterPin::Attiny85FasterPin(uint8_t, uint8_t)':
/home/ellie/Arduino/libraries/attiny85FasterPin/src/Attiny85FasterPin.cpp:9:15: error: 'analogInputToDigitalPin' was not declared in this scope
         pin = analogInputToDigitalPin((pin & 127));
               ^~~~~~~~~~~~~~~~~~~~~~~
/home/ellie/Arduino/libraries/attiny85FasterPin/src/Attiny85FasterPin.cpp:9:15: note: suggested alternative: 'analogInPinToBit'
         pin = analogInputToDigitalPin((pin & 127));
               ^~~~~~~~~~~~~~~~~~~~~~~
               analogInPinToBit
exit status 1
Error compiling for board ATtiny25/45/85.

any suggestions? do i need to downgrade my IDE?

**Comment by blinkinglight** [comment]
hey, 
can you try Attiny85IO?

**Comment by cybergrunge-ops** [comment]
i get the same message

**Comment by blinkinglight** [comment]
ok i will check today why this happens.

**Comment by blinkinglight** [comment]
> i get the same message

pushed update. i dont know when arduino library manager updates, but for now you can download repo as zip and import library. should work.

**Comment by cybergrunge-ops** [comment]
works perfectly! thank you! this library is just a bit smaller than some of the other ones out there so im glad it works now
